apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubelet-serving-cert-approver
resources:
  # TODO: renovate
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/refs/tags/v0.10.1/deploy/standalone-install.yaml
