apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.2.6/manifests/install.yaml
  - ops-app-project.yaml
  - ops-namespace.yaml
